"""Genome GA orchestration."""

from __future__ import annotations

import random
import re
from datetime import UTC, datetime
from enum import StrEnum
from math import ceil
from typing import Protocol

from pydantic import BaseModel, ConfigDict, Field, model_validator

from goagentx.core.strategy import Strategy, StrategyStatus
from goagentx.evolution.crossover import CrossoverKind, StrategyCrossover
from goagentx.evolution.mutation import MutationKind, StrategyMutator
from goagentx.evolution.selection import (
    ParentSelectionResult,
    ParentSelectionSettings,
    ParentSelector,
    TaskRunHistoryStore,
)


class GenomeGAError(RuntimeError):
    """Raised when Genome GA cannot generate a usable population."""


class GenomeGAOperation(StrEnum):
    """Candidate generation operation used by Genome GA."""

    CROSSOVER = "crossover"
    MUTATION = "mutation"


class GenomeGARegistry(Protocol):
    """Strategy registry surface needed by Genome GA."""

    def list_by_status(self, status: str | StrategyStatus) -> list[Strategy]:
        """List strategies with a lifecycle status."""

    def create(self, strategy: Strategy) -> Strategy:
        """Persist a new candidate strategy."""


class StrictModel(BaseModel):
    """Base model that rejects unknown Genome GA fields."""

    model_config = ConfigDict(extra="forbid")


class GenomeGASettings(StrictModel):
    """Population generation settings for Genome GA."""

    population_size: int = Field(default=20, ge=2)
    elite_ratio: float = Field(default=0.2, ge=0.0, lt=1.0)
    mutation_rate: float = Field(default=0.2, ge=0.0, le=1.0)
    selection_ratio: float = Field(default=0.6, gt=0.0, le=1.0)
    min_parent_count: int = Field(default=2, ge=2)
    max_runs_per_strategy: int = Field(default=50, gt=0)
    source_statuses: list[StrategyStatus] = Field(
        default_factory=lambda: [
            StrategyStatus.CHAMPION,
            StrategyStatus.SHADOW,
            StrategyStatus.CANARY,
            StrategyStatus.CANDIDATE,
            StrategyStatus.RETIRED,
        ]
    )
    crossover_kinds: list[CrossoverKind] = Field(
        default_factory=lambda: [
            CrossoverKind.UNIFORM,
            CrossoverKind.PROMPT_MODULE,
        ]
    )
    mutation_kinds: list[MutationKind] = Field(default_factory=lambda: list(MutationKind))
    candidate_id_prefix: str | None = Field(default=None, min_length=1)

    @model_validator(mode="after")
    def validate_operation_sources(self) -> "GenomeGASettings":
        """Ensure GA can choose sources for configured operations."""
        if not self.source_statuses:
            raise ValueError("source_statuses must not be empty")
        if self.mutation_rate < 1.0 and not self.crossover_kinds:
            raise ValueError("crossover_kinds must not be empty when crossover is enabled")
        if self.mutation_rate > 0.0 and not self.mutation_kinds:
            raise ValueError("mutation_kinds must not be empty when mutation is enabled")
        return self


class GenomeGACandidateResult(StrictModel):
    """One candidate generated by Genome GA."""

    candidate: Strategy
    operation: GenomeGAOperation
    crossover_kind: CrossoverKind | None = None
    mutation_kind: MutationKind | None = None


class GenomeGAResult(StrictModel):
    """Genome GA population generation result."""

    task_type: str | None = None
    settings: GenomeGASettings
    parent_selection: ParentSelectionResult
    elite_pool: list[Strategy]
    candidate_pool: list[GenomeGACandidateResult]
    population: list[Strategy]
    reason: str

    @property
    def candidate_ids(self) -> list[str]:
        """Return generated candidate ids in creation order."""
        return [item.candidate.id for item in self.candidate_pool]

    @property
    def elite_ids(self) -> list[str]:
        """Return elite strategy ids in rank order."""
        return [strategy.id for strategy in self.elite_pool]

    @property
    def crossover_count(self) -> int:
        """Return number of crossover-generated candidates."""
        return sum(
            item.operation is GenomeGAOperation.CROSSOVER
            for item in self.candidate_pool
        )

    @property
    def mutation_count(self) -> int:
        """Return number of mutation-generated candidates."""
        return sum(
            item.operation is GenomeGAOperation.MUTATION for item in self.candidate_pool
        )


def run_genome_ga(
    *,
    registry: GenomeGARegistry,
    task_store: TaskRunHistoryStore,
    mutator: StrategyMutator,
    crossover: StrategyCrossover,
    settings: GenomeGASettings | None = None,
    task_type: str | None = None,
    seed: int | None = 0,
) -> GenomeGAResult:
    """Generate the next GA population and persist new candidates."""
    resolved_settings = settings or GenomeGASettings()
    rng = random.Random(seed)
    source_strategies = _collect_source_strategies(
        registry,
        statuses=resolved_settings.source_statuses,
    )
    parent_selection = ParentSelector(
        task_store,
        ParentSelectionSettings(
            selection_ratio=resolved_settings.selection_ratio,
            min_parent_count=resolved_settings.min_parent_count,
            elite_count=_elite_count(
                population_size=resolved_settings.population_size,
                elite_ratio=resolved_settings.elite_ratio,
            ),
            max_runs_per_strategy=resolved_settings.max_runs_per_strategy,
        ),
    ).select(source_strategies, task_type=task_type)
    if parent_selection.insufficient_parent_pool:
        raise GenomeGAError(
            f"insufficient parent pool for Genome GA: {parent_selection.reason}"
        )

    parent_pool = parent_selection.parent_pool
    _ensure_compatible_parent_pair(parent_pool)

    elite_pool = parent_selection.elite_pool
    candidate_count = resolved_settings.population_size - len(elite_pool)
    mutation_slots = _mutation_slots(
        candidate_count=candidate_count,
        mutation_rate=resolved_settings.mutation_rate,
        rng=rng,
    )
    candidate_prefix = _candidate_id_prefix(
        configured_prefix=resolved_settings.candidate_id_prefix,
        task_type=task_type,
    )

    candidate_pool: list[GenomeGACandidateResult] = []
    for index in range(candidate_count):
        if index in mutation_slots:
            candidate_result = _generate_mutation_candidate(
                registry=registry,
                mutator=mutator,
                parent_pool=parent_pool,
                settings=resolved_settings,
                rng=rng,
                candidate_id=_candidate_id(
                    prefix=candidate_prefix,
                    index=index + 1,
                    operation=GenomeGAOperation.MUTATION,
                ),
            )
        else:
            candidate_result = _generate_crossover_candidate(
                registry=registry,
                crossover=crossover,
                parent_pool=parent_pool,
                settings=resolved_settings,
                rng=rng,
                candidate_id=_candidate_id(
                    prefix=candidate_prefix,
                    index=index + 1,
                    operation=GenomeGAOperation.CROSSOVER,
                ),
            )
        candidate_pool.append(candidate_result)

    return GenomeGAResult(
        task_type=task_type,
        settings=resolved_settings,
        parent_selection=parent_selection,
        elite_pool=elite_pool,
        candidate_pool=candidate_pool,
        population=[*elite_pool, *[item.candidate for item in candidate_pool]],
        reason="generated",
    )


def _collect_source_strategies(
    registry: GenomeGARegistry,
    *,
    statuses: list[StrategyStatus],
) -> list[Strategy]:
    strategies_by_id: dict[str, Strategy] = {}
    for status in statuses:
        for strategy in registry.list_by_status(status):
            strategies_by_id.setdefault(strategy.id, strategy)
    return list(strategies_by_id.values())


def _elite_count(*, population_size: int, elite_ratio: float) -> int:
    if elite_ratio <= 0.0:
        return 0
    return min(max(1, ceil(population_size * elite_ratio)), population_size - 1)


def _mutation_slots(
    *,
    candidate_count: int,
    mutation_rate: float,
    rng: random.Random,
) -> set[int]:
    if candidate_count <= 0 or mutation_rate <= 0.0:
        return set()
    mutation_count = min(
        candidate_count,
        max(1, int(candidate_count * mutation_rate + 0.5)),
    )
    return set(rng.sample(range(candidate_count), mutation_count))


def _generate_mutation_candidate(
    *,
    registry: GenomeGARegistry,
    mutator: StrategyMutator,
    parent_pool: list[Strategy],
    settings: GenomeGASettings,
    rng: random.Random,
    candidate_id: str,
) -> GenomeGACandidateResult:
    parent = rng.choice(parent_pool)
    mutation_kind = rng.choice(settings.mutation_kinds)
    candidate = mutator.mutate(
        parent,
        kind=mutation_kind,
        candidate_id=f"{candidate_id}-{mutation_kind.value}",
    )
    created = registry.create(candidate)
    return GenomeGACandidateResult(
        candidate=created,
        operation=GenomeGAOperation.MUTATION,
        mutation_kind=mutation_kind,
    )


def _generate_crossover_candidate(
    *,
    registry: GenomeGARegistry,
    crossover: StrategyCrossover,
    parent_pool: list[Strategy],
    settings: GenomeGASettings,
    rng: random.Random,
    candidate_id: str,
) -> GenomeGACandidateResult:
    parent_a, parent_b = _choose_parent_pair(parent_pool, rng=rng)
    crossover_kind = rng.choice(settings.crossover_kinds)
    candidate = crossover.crossover(
        parent_a,
        parent_b,
        kind=crossover_kind,
        candidate_id=f"{candidate_id}-{crossover_kind.value}",
    )
    created = registry.create(candidate)
    return GenomeGACandidateResult(
        candidate=created,
        operation=GenomeGAOperation.CROSSOVER,
        crossover_kind=crossover_kind,
    )


def _ensure_compatible_parent_pair(parent_pool: list[Strategy]) -> None:
    if not _compatible_parent_pairs(parent_pool):
        raise GenomeGAError("parent pool does not contain a compatible crossover pair")


def _choose_parent_pair(
    parent_pool: list[Strategy],
    *,
    rng: random.Random,
) -> tuple[Strategy, Strategy]:
    compatible_pairs = _compatible_parent_pairs(parent_pool)
    if not compatible_pairs:
        raise GenomeGAError("parent pool does not contain a compatible crossover pair")
    return rng.choice(compatible_pairs)


def _compatible_parent_pairs(parent_pool: list[Strategy]) -> list[tuple[Strategy, Strategy]]:
    pairs: list[tuple[Strategy, Strategy]] = []
    for index, parent_a in enumerate(parent_pool):
        for parent_b in parent_pool[index + 1 :]:
            if _parents_are_compatible(parent_a, parent_b):
                pairs.append((parent_a, parent_b))
    return pairs


def _parents_are_compatible(parent_a: Strategy, parent_b: Strategy) -> bool:
    if parent_a.id == parent_b.id:
        return False
    if parent_a.task_type is None or parent_b.task_type is None:
        return True
    return parent_a.task_type == parent_b.task_type


def _candidate_id_prefix(
    *,
    configured_prefix: str | None,
    task_type: str | None,
) -> str:
    if configured_prefix is not None:
        return configured_prefix
    domain = _slug(task_type or "global")
    timestamp = datetime.now(UTC).strftime("%Y%m%d%H%M%S%f")
    return f"ga-{domain}-{timestamp}"


def _candidate_id(
    *,
    prefix: str,
    index: int,
    operation: GenomeGAOperation,
) -> str:
    return f"{prefix}-{index:02d}-{operation.value}"


def _slug(value: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "-", value).strip("-").lower()
    return slug or "global"
